package buoy.gui;

import buoy.common.BuoyException;
import buoy.data.BuoyParserErrorHandler;
import buoy.data.BuoyReader;
import buoy.data.BuoyWriter;
import buoy.model.Buoy;
import buoy.model.BuoyCatcher;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shankar Krishnan
 */
public class BuoyCatcherDialog extends javax.swing.JDialog implements BuoyParserErrorHandler
{

    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    // Define a client property identifier in use with a cell renderer
    // to mark favorite buoys
    public static final String CLIENT_PROPERTY_BUOY_LIST = "CLIENT_PROPERTY_BUOY_LIST";

    // Singleton top level classes for the model and data compartments
    private BuoyCatcher buoyCatcher = null;
    private BuoyReader buoyReader = null;
    private BuoyWriter buoyWriter = null;

    /**
     * Add PropertyChangeListener.
     *
     * @param listener listens for changes to data declared as properties
     */
    public void addPropertyChangeListener(PropertyChangeListener listener)
    {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener removes previously registered listeners
     */
    public void removePropertyChangeListener(PropertyChangeListener listener)
    {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    /**
     *
     * @param parent the Frame parent of the main BuoyCatcher dialog
     * @param modal set to true for the BuoyCatcher application
     */
    public BuoyCatcherDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();

        tfLat.setText(BuoyCatcher.DEFAULT_LATITUDE);
        tfLong.setText(BuoyCatcher.DEFAULT_LONGITUDE);
        spinRadius.getModel().setValue(new Integer(BuoyCatcher.DEFAULT_SEARCH_RADIUS_NM));

        allBuoyPanel.setBuoyCatcherDialog(this);
        favoriteBuoysPanel.setBuoyCatcherDialog(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        tfLat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tabMain = new javax.swing.JTabbedPane();
        allBuoyPanel = new buoy.gui.AllBuoyPanel();
        favoriteBuoysPanel = new buoy.gui.FavoriteBuoysPanel();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spinRadius = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfLong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buoy Catcher");

        jLabel1.setText("Search Location:");

        tfLat.setText("40.000 N");
        tfLat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfLatActionPerformed(evt);
            }
        });

        jLabel3.setText("(NN.nnn N/S)");

        tabMain.addTab("All Buoys", allBuoyPanel);
        tabMain.addTab("Favorite Buoys", favoriteBuoysPanel);

        btnSearch.setText("Refresh");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Radius:");

        spinRadius.setModel(new javax.swing.SpinnerNumberModel(100, 50, 200, 5));

        jLabel4.setText("Nautical Miles");

        jLabel5.setText("Latitude:");

        jLabel6.setText("Longitude:");

        tfLong.setText("73.000 W");
        tfLong.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfLongActionPerformed(evt);
            }
        });

        jLabel7.setText("(NNN.nnn E/W)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinRadius))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfLong, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnClose)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearch, tfLong});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClose)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(spinRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        dispose();
        cleanupAndExit();

    }//GEN-LAST:event_btnCloseActionPerformed

    public void cleanupAndExit()
    {
        buoyCatcher.saveData();
        System.exit(0);
    }

    private void tfLatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfLatActionPerformed
    {//GEN-HEADEREND:event_tfLatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLatActionPerformed

    private void tfLongActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfLongActionPerformed
    {//GEN-HEADEREND:event_tfLongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLongActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchActionPerformed
    {//GEN-HEADEREND:event_btnSearchActionPerformed

        int radius = ((Integer) spinRadius.getModel().
                getValue());
        buoyCatcher.refreshBuoyList(tfLat.getText(), tfLong.getText(), radius);
        allBuoyPanel.populateBuoyList(buoyCatcher.getAllBuoys());
        
        favoriteBuoysPanel.populateBuoyList(new ArrayList<Buoy>());
        favoriteBuoysPanel.populateBuoyList(buoyCatcher.getFavoriteBuoys());
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BuoyCatcherDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BuoyCatcherDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BuoyCatcherDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BuoyCatcherDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                BuoyCatcherDialog dialog = new BuoyCatcherDialog(new javax.swing.JFrame(), true);
                dialog.initialize();
            }

        });
    }

    /**
     * This function is the main entry point from the static main function
     */
    public void initialize()
    {
        buoyWriter = new BuoyWriter();
        buoyReader = new BuoyReader();

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e)
            {
                cleanupAndExit();
            }
        });

        BuoyCatcher bc = new BuoyCatcher(buoyReader, buoyWriter);
        bc.restoreSession(this);
        bc.findBuoys();

        // Load the BuoyCatcher data into the GUI
        setBuoyCatcher(bc);

        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private buoy.gui.AllBuoyPanel allBuoyPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private buoy.gui.FavoriteBuoysPanel favoriteBuoysPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner spinRadius;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextField tfLat;
    private javax.swing.JTextField tfLong;
    // End of variables declaration//GEN-END:variables

    private void setBuoyCatcher(BuoyCatcher buoyCatcher)
    {
        this.buoyCatcher = buoyCatcher;

        // Initilaize search options to data read from the file.
        tfLat.setText(buoyCatcher.getSearchLatitude());
        tfLong.setText(buoyCatcher.getSearchLongitude());
        spinRadius.getModel().setValue(buoyCatcher.getSearchRadius());

        allBuoyPanel.setBuoyCatcher(buoyCatcher);
        favoriteBuoysPanel.setBuoyCatcher(buoyCatcher);
    }

    void markFavorite(boolean bFav)
    {
        favoriteBuoysPanel.populateBuoyList(buoyCatcher.getFavoriteBuoys());

        // Need to cause a refresh of the all buoys screen
        
        allBuoyPanel.populateBuoyList(new ArrayList<Buoy>());
        allBuoyPanel.populateBuoyList(buoyCatcher.getAllBuoys());
    }

    @Override
    public void handleParsingError(BuoyException error)
    {
        //TBD
    }

}
