/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buoy.gui;

import buoy.Buoy;
import buoy.BuoyCatcher;
import java.util.List;

/**
 *
 * @author Sanjana
 */
public class FavoriteBuoysPanel extends BuoyPanel
{

    /**
     * Creates new form FavoriteBuoysPanel
     */
    public FavoriteBuoysPanel()
    {
        super();
        customize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  private void customize()
    {
         setMode(BuoyPanel.MODE_FAVORITES);
    }

     void setBuoyCatcher(BuoyCatcher catcher)
    {
        buoyCatcher = catcher;
  
        List <Buoy>  newList = buoyCatcher.getFavoriteBuoys();
        populateBuoyList(newList);
        
    }
}

